[package]
name                 = "catix-server"
description          = "Catix server"
version.workspace    = true
authors.workspace    = true
homepage.workspace   = true
readme.workspace     = true
repository.workspace = true
license.workspace    = true
edition.workspace    = true
categories.workspace = true
keywords.workspace   = true

[dependencies]
tracing = { workspace = true }

serde      = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

async-trait = { workspace = true }
futures = { workspace = true }
sigfinn = { workspace = true }
tokio = { workspace = true, features = [
  "fs",
  "macros",
  "rt-multi-thread",
  "sync",
] }
tokio-stream = { workspace = true, features = ["net"] }

axum = { workspace = true }
http = { workspace = true }
reqwest = { workspace = true, default-features = false, features = [
  "json",
  "rustls",
  "rustls-tls",
  "stream",
] }
tower = { workspace = true, features = ["timeout"] }
tower-http = { workspace = true, features = ["trace"] }

prometheus = { workspace = true }
semver     = { workspace = true }
snafu      = { workspace = true }

catix-base    = { path = "../base" }
catix-metrics = { path = "../metrics" }

[lints]
workspace = true
